"""Persistence contracts for the application layer."""
from __future__ import annotations

from datetime import datetime
from typing import Any, Mapping, Protocol, Sequence


class TrainsetRepository(Protocol):
    async def list_all(self, status: str | None = None) -> list[Mapping[str, Any]]: ...
    async def get(self, trainset_id: str) -> Mapping[str, Any] | None: ...
    async def update(self, trainset_id: str, updates: Mapping[str, Any]) -> bool: ...


class OptimizationRepository(Protocol):
    async def save_run(self, payload: Mapping[str, Any]) -> str: ...
    async def get_latest_decisions(self) -> Sequence[Mapping[str, Any]] | None: ...
    async def get_latest_history(self) -> Mapping[str, Any] | None: ...


class ReviewRepository(Protocol):
    async def list_reviews(self, limit: int = 50) -> Sequence[Mapping[str, Any]]: ...
    async def create_review(self, payload: Mapping[str, Any]) -> str: ...


class UserRepository(Protocol):
    async def get_by_username(self, username: str) -> Mapping[str, Any] | None: ...
    async def get_by_id(self, user_id: str) -> Mapping[str, Any] | None: ...
    async def save(self, payload: Mapping[str, Any]) -> str: ...
    async def update(self, user_id: str, updates: Mapping[str, Any]) -> bool: ...
    async def delete_pending(self, user_id: str) -> bool: ...
    async def list_pending(self) -> Sequence[Mapping[str, Any]]: ...


class AssignmentRepository(Protocol):
    """Persistence contract for assignment queries and state transitions."""
    async def list(self, *, status: str | None = None, trainset_id: str | None = None, created_after: datetime | None = None, created_before: datetime | None = None, priority: int | None = None, limit: int = 100, offset: int = 0) -> Sequence[Mapping[str, Any]]: ...
    async def get(self, assignment_id: str) -> Mapping[str, Any] | None: ...
    async def insert(self, payload: Mapping[str, Any]) -> str: ...
    async def insert_many(self, payloads: Sequence[Mapping[str, Any]]) -> int: ...
    async def total_count(self) -> int: ...
    async def count_status(self, status: str) -> int: ...
    async def count_high_priority(self, minimum: int = 4) -> int: ...
    async def average_confidence(self) -> float: ...
    async def count_with_violations(self) -> int: ...
    async def approve_pending(self, assignment_ids: Sequence[str], user_id: str, comments: str | None, when: datetime) -> int: ...
    async def override_pending(self, assignment_id: str, user_id: str, reason: str, override_decision: str, when: datetime) -> Mapping[str, Any] | None: ...
    async def list_assigned_trainset_ids(self) -> set[str]: ...
    async def get_by_trainset(self, trainset_id: str) -> Mapping[str, Any] | None: ...


class DashboardRepository(Protocol):
    """Read-only persistence contract for dashboard aggregation."""
    async def list_trainsets(self) -> Sequence[Mapping[str, Any]]: ...
    async def get_latest_induction(self) -> Mapping[str, Any] | None: ...
    async def count_pending_assignments(self) -> int: ...
    async def list_assigned_trainset_ids(self) -> set[str]: ...
    async def list_alert_candidates(self) -> Sequence[Mapping[str, Any]]: ...
    async def get_recent_optimization_history(self, limit: int = 7) -> Sequence[Mapping[str, Any]]: ...


class AuditRepository(Protocol):
    """Persistence contract for append-only audit records."""
    async def create(self, payload: Mapping[str, Any]) -> str: ...
    async def list(self, *, start: datetime | None = None, end: datetime | None = None, user_id: str | None = None, action: str | None = None, limit: int = 10000) -> Sequence[Mapping[str, Any]]: ...


class SensorRepository(Protocol):
    """Persistence contract for sensor/time-series ingestion."""
    async def write_sensor_data(self, payload: Mapping[str, Any]) -> bool: ...
    async def write_downsampled(self, records: Sequence[Mapping[str, Any]]) -> int: ...
