"""Persistence contracts for the application layer."""
from __future__ import annotations
from typing import Any, Mapping, Protocol, Sequence


class TrainsetRepository(Protocol):
    async def list_all(self, status: str | None = None) -> list[Mapping[str, Any]]: ...
    async def get(self, trainset_id: str) -> Mapping[str, Any] | None: ...
    async def update(self, trainset_id: str, updates: Mapping[str, Any]) -> bool: ...


class OptimizationRepository(Protocol):
    async def save_run(self, payload: Mapping[str, Any]) -> str: ...
    async def get_latest_decisions(self) -> Sequence[Mapping[str, Any]] | None: ...
    async def get_latest_history(self) -> Mapping[str, Any] | None: ...


class ReviewRepository(Protocol):
    async def list_reviews(self, limit: int = 50) -> Sequence[Mapping[str, Any]]: ...
    async def create_review(self, payload: Mapping[str, Any]) -> str: ...


class UserRepository(Protocol):
    async def get_by_username(self, username: str) -> Mapping[str, Any] | None: ...
    async def save(self, payload: Mapping[str, Any]) -> str: ...
